module.exports = {
    rules: {
        "type-enum": [
            2,
            "always",
            [
                "feat",
                "fix",
                "docs",
                "style",
                "refactor",
                "perf",
                "test",
                "build",
                "ci",
                "chore",
                "revert",
            ],
        ],
        "type-case": [2, "always", "lower-case"],
        "type-empty": [2, "never"],
        "subject-empty": [2, "never"],
        "subject-full-stop": [2, "never", "."],
        "header-max-length": [2, "always", 100],
        "body-empty": [2, "never"],
        "body-leading-blank": [2, "always"],
        "body-max-line-length": [2, "always", 100],
        "footer-leading-blank": [2, "always"],
    },
};
