<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Core" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.4" />
    <PackageReference Include="NSubstitute" Version="5.0.0" />
    <PackageReference Include="TUnit" Version="0.25.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\redmuffin.Blazor.StaticWeb.Api\redmuffin.Blazor.StaticWeb.Api.csproj" />
  </ItemGroup>

</Project>
