namespace redmuffin.Blazor.StaticWeb.Features.IconsPage;

public partial class Icons
{
    private static readonly string[] IconNames =
    [
        "ad", "add", "address-book", "address-card", "adjust", "air-freshener", "allergies", "ambulance",
        "american-sign-language-interpreting", "angle-double-down", "angle-double-left", "angle-double-right", "angle-double-up", "angry",
        "apple-alt", "archive", "area-chart", "arrow-alt-circle-down", "arrow-alt-circle-left", "arrow-alt-circle-right",
        "arrow-alt-circle-up", "arrow-circle-down", "arrow-circle-left", "arrow-circle-right", "arrow-circle-up", "arrow-down-1-9",
        "arrow-down-9-1", "arrow-down-a-z", "arrow-down-long", "arrow-down-short-wide", "arrow-down-wide-short", "arrow-down-z-a",
        "arrow-left-long", "arrow-left-rotate", "arrow-pointer", "arrow-right-arrow-left", "arrow-right-from-bracket",
        "arrow-right-from-file", "arrow-right-long", "arrow-right-rotate", "arrow-right-to-bracket", "arrow-right-to-file",
        "arrow-rotate-back", "arrow-rotate-backward", "arrow-rotate-forward", "arrow-rotate-left", "arrow-rotate-right", "arrow-turn-down",
        "arrow-turn-up", "arrow-up-1-9", "arrow-up-9-1", "arrow-up-a-z", "arrow-up-long", "arrow-up-right-from-square",
        "arrow-up-short-wide", "arrow-up-wide-short", "arrow-up-z-a", "arrows", "arrows-alt", "arrows-alt-h", "arrows-alt-v",
        "arrows-h", "arrows-rotate", "arrows-up-down", "asl-interpreting", "assistive-listening-systems", "atlas", "automobile",
        "baby-carriage", "backspace", "backward-fast", "backward-step", "bag-shopping", "bahai", "balance-scale", "balance-scale-left",
        "balance-scale-right", "ban", "ban-smoking", "band-aid", "bank", "bar-chart", "bars", "bars-progress", "bars-staggered",
        "baseball", "basket-shopping", "basketball", "bath", "battery", "battery-0", "battery-2", "battery-3", "battery-4",
        "battery-5", "battery-car", "bed-pulse", "beer", "behance-square", "bell-concierge", "bible",
        "biking", "birthday-cake", "blackboard", "blind", "bolt", "book-dead", "book-journal-whills", "book-open-reader",
        "book-quran", "book-tanakh", "border-style", "boxes", "boxes-alt", "briefcase-clock", "broadcast-tower",
        "broom-ball", "building-columns", "burger", "burn", "bus-alt", "cab", "cable-car", "cake", "calendar-alt",
        "calendar-times", "camera", "car-alt", "car-burst", "caret-square-down", "caret-square-left", "caret-square-right",
        "caret-square-up", "cart-flatbed", "cart-flatbed-suitcase", "cart-shopping", "chain", "chain-broken", "chain-slash",
        "chalkboard-teacher", "champagne-glasses", "chart-line", "chart-pie", "check-circle", "check-square", "check-to-slot",
        "chevron-circle-down", "chevron-circle-left", "chevron-circle-right", "chevron-circle-up", "child-combatant", "circle-dollar-to-slot",
        "circle-dot", "circle-exclamation", "circle-h", "circle-info", "circle-minus", "circle-pause", "circle-play", "circle-plus",
        "circle-question", "circle-radiation", "circle-stop", "circle-user", "circle-xmark", "clinic-medical", "clock",
        "clock-rotate-left", "close", "cloud-arrow-down", "cloud-arrow-up", "cloud-bolt", "cloud-download", "cloud-upload", "cny",
        "cocktail", "coffee", "cog", "cogs", "columns", "comment-alt", "comment-dots", "comment-sms", "compass-drafting",
        "compress-alt", "compress-arrows-alt", "computer-mouse", "contact-card", "credit-card", "crop-alt", "cut", "cutlery",
        "dashboard", "deaf", "deafness", "dedent", "desktop", "diagnoses", "diagram-project", "diamond-turn-right", "digging",
        "digital-tachograph", "dizzy", "dollar", "dollar-sign", "dolly", "down-long", "drivers-license",
        "droplet", "droplet-slash", "ear-deaf", "earth", "earth-africa", "earth-america", "earth-americas", "earth-asia",
        "earth-europe", "earth-oceania", "edit", "ellipsis", "ellipsis-v", "envelope-square", "envelopes-bulk", "eur", "euro",
        "exchange-alt", "exclamation-triangle", "expand-alt", "expand-arrows-alt", "external-link-alt", "external-link-square",
        "external-link-square-alt", "eye-dropper", "eye-dropper-empty", "eye-low-vision", "face-flushed", "face-frown", "face-frown-open",
        "face-grimace", "face-grin", "face-grin-beam", "face-grin-beam-sweat", "face-grin-hearts", "face-grin-squint",
        "face-grin-squint-tears", "face-grin-stars", "face-grin-tears", "face-grin-tongue", "face-grin-tongue-squint",
        "face-grin-tongue-wink", "face-grin-wide", "face-grin-wink", "face-kiss", "face-kiss-beam", "face-kiss-wink-heart", "face-laugh",
        "face-laugh-beam", "face-laugh-squint", "face-laugh-wink", "face-meh", "face-meh-blank", "face-rolling-eyes", "face-sad-cry",
        "face-sad-tear", "face-smile", "face-smile-beam", "face-smile-wink", "face-surprise", "face-tired", "fade",
        "fast-forward", "feather-alt", "feed", "female", "fighter-jet", "file-alt", "file-archive", "file-arrow-down",
        "file-arrow-up", "file-clipboard", "file-edit", "file-lines", "file-medical-alt", "filter-circle-dollar", "fire-alt",
        "first-aid", "fist-raised", "floppy-disk", "folder", "font-awesome", "font-awesome-alt",
        "font-awesome-flag", "football", "forward-step", "futbol", "futbol-ball", "gauge", "gauge-high", "gauge-med", "gauge-simple",
        "gauge-simple-high", "gauge-simple-med", "gavel", "gbp", "git-square", "github-square", "gitlab-square", "glass-martini",
        "glass-martini-alt", "glass-whiskey", "golf-ball", "google-plus-square", "graduation-cap", "grip", "h-square",
        "hacker-news-square", "hand", "hand-back-fist", "hand-holding-dollar", "hand-holding-droplet", "hands",
        "hands-american-sign-language-interpreting", "hands-bubbles", "hands-helping", "hands-praying", "handshake-alt",
        "handshake-alt-slash", "hard-drive", "hard-hat", "hat-hard", "header", "headphones-alt", "heart-broken",
        "heart-music-camera-bolt", "heart-pulse", "hiking", "home", "home-alt", "home-lg", "home-lg-alt", "home-user", "hospital",
        "hospital-alt", "hot-tub", "hourglass", "hourglass-1", "hourglass-2", "hourglass-3", "house-chimney-crack", "house-laptop",
        "hryvnia", "id-card-alt", "ils", "image-portrait", "indian-rupee", "indian-rupee-sign", "instagram-square", "institution",
        "jpy", "js-square", "kickstarter", "krw", "ladder-water", "landmark-alt", "lastfm-square", "left-long", "level-down-alt",
        "level-up-alt", "link-slash", "list", "list-1-2", "list-alt", "list-check", "list-dots", "list-numeric", "location",
        "location-dot", "location-pin", "long-arrow-alt-right", "long-arrow-alt-up", "magic", "magic-wand-sparkles", "magnifying-glass",
        "magnifying-glass-dollar", "magnifying-glass-location", "magnifying-glass-minus", "magnifying-glass-plus", "mail-forward",
        "mail-reply", "mail-reply-all", "male", "map-location", "map-location-dot", "map-signs", "mars-stroke-h", "mars-stroke-up",
        "masks-theater", "medium", "medkit", "microphone-alt", "microphone-alt-slash", "minus", "minus-square", "mobile",
        "mobile-alt", "mobile-android", "mobile-android-alt", "money-bill-1", "money-bill-1-wave", "money-check-alt", "multiply",
        "museum", "note-sticky", "odnoklassniki-square", "paint-brush", "parking", "pastafarianism", "pen-alt", "pen-ruler",
        "pen-square", "pencil", "pencil-square", "people-arrows", "people-carry", "percent", "person-praying", "person-running",
        "person-skating", "person-skiing", "person-skiing-nordic", "person-snowboarding", "person-swimming", "person-walking", "phone-alt",
        "phone-square", "phone-square-alt", "phone-volume", "photo-film", "pied-piper-square", "ping-pong-paddle-ball", "pinterest-square",
        "plus-square", "poll", "poll-h", "poo-bolt", "pound-sign", "prescription-bottle-alt", "quidditch", "quote-left",
        "quote-right", "random", "rectangle-times", "rectangle-xmark", "reddit-square", "redo-alt", "refresh", "remove",
        "remove-format", "rendact", "reorder", "right-from-bracket", "right-to-bracket", "rmb", "rod-asclepius", "rod-snake",
        "rotate", "rotate-back", "rotate-backward", "rotate-forward", "rotate-left", "rouble", "rss-square", "rub", "ruble",
        "rupee", "screwdriver-wrench", "scroll-torah", "seedling", "shapes", "share-alt", "share-alt-square",
        "share-from-square", "shekel", "shekel-sign", "sheqel", "shield", "shield-alt", "shipping-fast", "shirt", "shop",
        "shop-slash", "shuttle-space", "shuttle-van", "sign", "sign-language", "signal", "signal-5", "slack", "sliders",
        "snapchat", "snapchat-square", "sort", "sort-alpha-asc", "sort-alpha-desc", "sort-amount-asc", "sort-amount-desc",
        "sort-asc", "sort-desc", "sort-numeric-asc", "sort-numeric-desc", "spoon", "square-root-alt", "square-xmark",
        "staff-aesculapius", "star-half-alt", "subway", "swimming-pool",
        "t-shirt", "table-cells", "table-cells-large", "table-list", "table-tennis", "tablet", "tablet-alt", "tachometer",
        "tachometer-alt", "teletype", "television", "temperature-0", "temperature-1", "temperature-2", "temperature-3",
        "temperature-4", "temperature-arrow-down", "temperature-arrow-up", "temperature-empty", "temperature-full", "temperature-half",
        "temperature-quarter", "temperature-three-quarters", "tenge", "thermometer-0", "thermometer-1", "thermometer-2", "thermometer-3",
        "thermometer-4", "thumb-tack", "thumb-tack-slash", "ticket-alt", "times", "times-circle", "times-rectangle", "times-square",
        "transgender", "trash-alt", "trash-arrow-up", "trash-can-arrow-up", "triangle-exclamation", "truck-loading", "try",
        "turkish-lira", "tv", "unlock-alt", "user-alt", "user-alt-slash", "user-cog", "user-doctor", "user-edit", "user-friends",
        "user-times", "users-cog", "video", "volleyball", "volume-down", "volume-high", "volume-mute", "volume-times", "weight",
        "wheat-alt", "wheelchair-alt", "wifi", "wifi-3", "wine-glass-alt", "wirsindhandwerk", "won", "yen"
    ];
}