<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>redmuffin.Blazor.StaticWeb.Modules.ApiHealth.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\redmuffin.Blazor.StaticWeb.Modules\ApiHealth\ApiHealth.csproj" />
    <ProjectReference Include="..\..\..\src\redmuffin.Blazor.StaticWeb.Modules\ApiHealth.Contracts\ApiHealth.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\redmuffin.Blazor.StaticWeb.Common\redmuffin.Blazor.StaticWeb.Common.csproj" />
  </ItemGroup>

</Project>
